-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid,
  target_audience text DEFAULT 'all'::text CHECK (target_audience = ANY (ARRAY['all'::text, 'students'::text, 'teachers'::text, 'admins'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.assignment_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid,
  user_id uuid,
  submission_text text,
  file_url text,
  submitted_at timestamp with time zone DEFAULT now(),
  graded_by uuid,
  grade integer,
  feedback text,
  graded_at timestamp with time zone,
  status text DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'graded'::text, 'late'::text, 'missing'::text])),
  student_id uuid,
  portal_user_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT assignment_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_submissions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id),
  CONSTRAINT assignment_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT assignment_submissions_graded_by_fkey FOREIGN KEY (graded_by) REFERENCES public.portal_users(id),
  CONSTRAINT assignment_submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT assignment_submissions_portal_user_id_fkey FOREIGN KEY (portal_user_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title text NOT NULL,
  description text,
  instructions text,
  due_date timestamp with time zone,
  max_points integer DEFAULT 100,
  assignment_type text CHECK (assignment_type = ANY (ARRAY['homework'::text, 'project'::text, 'quiz'::text, 'exam'::text, 'presentation'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  class_id uuid,
  CONSTRAINT assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.portal_users(id),
  CONSTRAINT assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  user_id uuid,
  status text DEFAULT 'present'::text CHECK (status = ANY (ARRAY['present'::text, 'absent'::text, 'late'::text, 'excused'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  student_id uuid,
  recorded_by uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.class_sessions(id),
  CONSTRAINT attendance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.portal_users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.cbt_exams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  program_id uuid,
  duration_minutes integer NOT NULL,
  total_questions integer NOT NULL,
  passing_score integer DEFAULT 50,
  is_active boolean DEFAULT true,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cbt_exams_pkey PRIMARY KEY (id),
  CONSTRAINT cbt_exams_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.cbt_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_id uuid,
  question_text text NOT NULL,
  question_type text DEFAULT 'multiple_choice'::text CHECK (question_type = ANY (ARRAY['multiple_choice'::text, 'true_false'::text, 'essay'::text, 'fill_blank'::text])),
  options jsonb,
  correct_answer text,
  points integer DEFAULT 1,
  order_index integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cbt_questions_pkey PRIMARY KEY (id),
  CONSTRAINT cbt_questions_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.cbt_exams(id)
);
CREATE TABLE public.cbt_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_id uuid,
  user_id uuid,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone,
  score integer,
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text, 'passed'::text, 'failed'::text])),
  answers jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cbt_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT cbt_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT cbt_sessions_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.cbt_exams(id)
);
CREATE TABLE public.class_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid,
  session_date date NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  topic text,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text,
  location text,
  meeting_url text,
  is_online boolean DEFAULT false,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text])),
  CONSTRAINT class_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT class_sessions_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid,
  teacher_id uuid,
  name text NOT NULL,
  description text,
  max_students integer,
  start_date date,
  end_date date,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'active'::text, 'completed'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  schedule text,
  current_students integer DEFAULT 0,
  school_id uuid,
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.portal_users(id),
  CONSTRAINT classes_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.course_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title text NOT NULL,
  description text,
  file_url text,
  file_type text CHECK (file_type = ANY (ARRAY['pdf'::text, 'video'::text, 'image'::text, 'document'::text, 'link'::text])),
  file_size integer,
  order_index integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_materials_pkey PRIMARY KEY (id),
  CONSTRAINT course_materials_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid,
  title text NOT NULL,
  description text,
  content text,
  duration_hours integer,
  order_index integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  teacher_id uuid,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT courses_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  program_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['student'::text, 'teacher'::text])),
  enrollment_date date NOT NULL DEFAULT CURRENT_DATE,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'dropped'::text, 'suspended'::text])),
  completion_date date,
  grade text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  progress_pct integer DEFAULT 0,
  last_activity_at timestamp with time zone,
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.generated_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  generated_by uuid,
  report_name text NOT NULL,
  report_data jsonb,
  file_url text,
  generated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT generated_reports_pkey PRIMARY KEY (id),
  CONSTRAINT generated_reports_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.report_templates(id),
  CONSTRAINT generated_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.portal_users(id)
);
CREATE TABLE public.grade_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  portal_user_id uuid,
  program_id uuid,
  total_assignments integer DEFAULT 0,
  graded_assignments integer DEFAULT 0,
  average_score numeric,
  highest_score numeric,
  lowest_score numeric,
  letter_grade text,
  generated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT grade_reports_pkey PRIMARY KEY (id),
  CONSTRAINT grade_reports_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT grade_reports_portal_user_id_fkey FOREIGN KEY (portal_user_id) REFERENCES public.portal_users(id),
  CONSTRAINT grade_reports_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid,
  title text NOT NULL,
  description text,
  lesson_type text CHECK (lesson_type = ANY (ARRAY['video'::text, 'interactive'::text, 'hands-on'::text, 'workshop'::text, 'coding'::text, 'reading'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'scheduled'::text, 'completed'::text])),
  duration_minutes integer,
  session_date timestamp with time zone,
  video_url text,
  content text,
  order_index integer,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT lessons_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.portal_users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid,
  recipient_id uuid,
  subject text,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.portal_users(id),
  CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'error'::text])),
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  action_url text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  program_id uuid,
  amount numeric NOT NULL,
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'card'::text, 'online'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  transaction_reference text,
  payment_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  student_id uuid,
  transaction_id text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT payments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.portal_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'teacher'::text, 'student'::text])),
  phone text,
  school_name text,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  profile_image_url text,
  bio text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  student_id uuid,
  is_deleted boolean DEFAULT false,
  last_login timestamp with time zone,
  school_id uuid,
  enrollment_type text CHECK (enrollment_type = ANY (ARRAY['school'::text, 'bootcamp'::text, 'online'::text])),
  CONSTRAINT portal_users_pkey PRIMARY KEY (id),
  CONSTRAINT portal_users_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT portal_users_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  duration_weeks integer,
  difficulty_level text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  price numeric,
  max_students integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT programs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.report_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  template_type text DEFAULT 'student_progress'::text CHECK (template_type = ANY (ARRAY['student_progress'::text, 'financial'::text, 'attendance'::text, 'performance'::text])),
  query_template text,
  parameters jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text,
  city text,
  state text,
  contact_person text,
  phone text,
  email text,
  student_count integer,
  created_at timestamp with time zone DEFAULT now(),
  school_type text,
  lga text,
  program_interest ARRAY,
  updated_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  enrollment_types ARRAY DEFAULT ARRAY['school'::text],
  CONSTRAINT schools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  program_id uuid,
  enrollment_date date NOT NULL DEFAULT CURRENT_DATE,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'dropped'::text, 'suspended'::text])),
  completion_date date,
  grade text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT student_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id)
);
CREATE TABLE public.student_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  portal_user_id uuid,
  course_id uuid,
  lessons_completed integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  assignments_completed integer DEFAULT 0,
  total_assignments integer DEFAULT 0,
  average_grade numeric,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_progress_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_progress_portal_user_id_fkey FOREIGN KEY (portal_user_id) REFERENCES public.portal_users(id),
  CONSTRAINT student_progress_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  age integer,
  email text,
  phone text,
  school text,
  created_at timestamp with time zone DEFAULT now(),
  grade text,
  gender text,
  parent_name text,
  course_interest text,
  preferred_schedule text,
  hear_about_us text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  full_name text,
  date_of_birth date,
  parent_email text,
  parent_phone text,
  school_name text,
  current_class text,
  city text,
  state text,
  country text DEFAULT 'Nigeria'::text,
  medical_conditions text,
  allergies text,
  previous_programming_experience text,
  interests text,
  goals text,
  approved_by uuid,
  approved_at timestamp with time zone,
  user_id uuid,
  student_number text,
  grade_level text,
  avatar_url text,
  enrollment_type text DEFAULT 'school'::text CHECK (enrollment_type = ANY (ARRAY['school'::text, 'bootcamp'::text, 'online'::text])),
  student_email text,
  heard_about_us text,
  parent_relationship text,
  school_id uuid,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.portal_users(id),
  CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id),
  CONSTRAINT students_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value text,
  description text,
  category text DEFAULT 'general'::text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teacher_schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  school_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  is_primary boolean DEFAULT false,
  notes text,
  CONSTRAINT teacher_schools_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_schools_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.portal_users(id),
  CONSTRAINT teacher_schools_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT teacher_schools_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.portal_users(id)
);
CREATE TABLE public.teachers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  subjects ARRAY DEFAULT '{}'::text[],
  experience_years integer DEFAULT 0,
  education text,
  bio text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT teachers_pkey PRIMARY KEY (id),
  CONSTRAINT teachers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.portal_users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  bio text,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  address text,
  city text,
  state text,
  country text DEFAULT 'Nigeria'::text,
  postal_code text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.portal_users(id)
);