#:schema node_modules/wrangler/config-schema.json
name = "rillcodwebsite"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_APP_URL = "https://rillcod.com"
NEXT_PUBLIC_SUPABASE_URL = "https://akaorqukdoawacvxsdij.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYW9ycXVrZG9hd2FjdnhzZGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMDg2MzgsImV4cCI6MjA4NzU4NDYzOH0.60US0KpUqtur_5YqPSX3qxPex1wkzAG7WX-WBmoMi-s"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY = "sb_publishable_ayfXqNoQdQQbDFskLBwoPA_qQQoZnC-"
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY = "pk_live_e5f065f4708f8f1c865131c5a40d2e937bd1515d"
NEXT_PUBLIC_LIVEKIT_URL = "[SENSITIVE]"
NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BIBaCy_MbkmVNVBrxQkfzaq6HsCzPtZc8Lp-_N2Apo_6iW17itdwOL5gLXR87DMdXugsNivJLBP43HAjW-n4eFs"
NEXT_PUBLIC_SUMMER_SCHOOL_WHATSAPP_GROUP = "[SENSITIVE]"
ENABLE_PAYMENTS = "true"
LIVEKIT_URL = "[SENSITIVE]"
R2_ENDPOINT = "https://718b36de1443954931b052a9594d329d.r2.cloudflarestorage.com"
R2_BUCKET_NAME = "rillcod-assests"
R2_ACCESS_KEY_ID = "d2258442245e101cddd6e56b02ffe250"
RESEND_FROM_EMAIL = "[SENSITIVE]"
WHATSAPP_API_URL = "https://graph.facebook.com/v19.0/1165370629985726/messages"
ADMIN_OPS_EMAIL = "rillcod@gmail.com"
