import type { SpineCourseMeta, SpineLessonSpec } from '@/lib/curriculum/school-spine-week';

const L = (
  subtopics: string[],
  objectives: string[],
  teacher: string[],
  students: string[],
  classwork: string,
  homework: string,
  check: string,
): SpineLessonSpec => ({
  subtopics,
  objectives,
  teacher,
  students,
  classwork: { title: 'In class', instructions: classwork },
  assignment: { title: 'Before next class', instructions: homework },
  check: { title: 'Look for', how: check },
  resources: ['Thonny or VS Code', 'Python 3', 'Projector'],
  tips: ['Type with them for the first example, then step back', 'If machines are few, one types, one reads the error aloud'],
});

export const PYTHON_COURSE_META: SpineCourseMeta = {
  title: 'Python for Beginners',
  overview:
    'Learners write Python they can run the same day. The year moves from print and variables, through decisions and loops, into lists, files and a small program they can show.',
  outcomes: [
    'Run a Python file and read a simple error message.',
    'Use variables, input, if/elif/else and loops in a short program.',
    'Store values in a list or dictionary and print them clearly.',
    'Finish a mini program, test it with two inputs, and explain what it does.',
  ],
  materials: ['Computers with Python 3', 'Projector', 'Exercise book'],
  tools: ['Python 3', 'Thonny'],
  assessmentStrategy:
    'Weekly running program, a practical checkpoint each term, and an end-of-term mini application.',
};

export const PYTHON_LESSONS: SpineLessonSpec[][] = [
  [
    L(
      ['What a program is', 'The editor and the Run button', 'print'],
      ['Open the editor and run a file', 'Use print to show a line of text'],
      ['Run print("Hello") on the projector and point at the output pane', 'Show Save then Run as a habit, not an afterthought'],
      ['Type a print of their name and a Nigerian food they like', 'Save the file as hello.py and run it'],
      'A program that prints two lines with no red error.',
      'Write what the Run button did, in one sentence.',
      'hello.py runs and shows their text.',
    ),
    L(
      ['Assignment with =', 'int, float, str', 'Names that mean something'],
      ['Store a value in a named variable', 'Print that variable'],
      ['Live-code rice_price = 800 and print it', 'Break a name that starts with a number and let them see the error'],
      ['Make three variables for prices in naira', 'Print each one with a label'],
      'Three named variables print without quotes around the numbers unless they are text.',
      'Which of your names is clearest? Why?',
      'Variables used; output shows numbers from the variables, not only typed text.',
    ),
    L(
      ['int() / str()', 'A type error', 'Clear output'],
      ['Fix a type error by converting a value', 'Print a labelled result'],
      ['Give three broken snippets: adding a number to a string, a typo, a missing bracket', 'Walk one fix, leave two for them'],
      ['Repair the three snippets in pairs', 'Write the cause of each error in the book'],
      'All three snippets run after the pair’s edits.',
      'Copy one error message and what you changed.',
      'Repaired programs run; pair can say what was wrong.',
    ),
    L(
      ['+ - * / // % **', 'BODMAS', '== != < >'],
      ['Write an arithmetic expression and print the result', 'Compare two numbers with a comparison operator'],
      ['Calculate a three-subject average on the board, then in Python', 'Show 7 / 2 versus 7 // 2'],
      ['Compute total and average for three scores', 'Print True/False for “average >= 50”'],
      'Average is calculated by the program, not typed as a finished number.',
      'Predict the output of 2 + 3 * 4, then check.',
      'Correct arithmetic and one comparison printed.',
    ),
    L(
      ['input()', 'int(input())', 'A reply that uses the answer'],
      ['Ask the user a question with input', 'Turn a numeric answer into int before doing maths'],
      ['Demo name and age, then age + 1', 'Crash it with a word in the age box, then talk about next week’s errors'],
      ['Ask for name and age and print next year’s age', 'Refuse to add age without int()'],
      'Program asks, waits, then prints a sentence that includes the typed name.',
      'What happens if someone types ten instead of 10?',
      'Interactive run using the learner’s own input.',
    ),
    L(
      ['f-strings or format', 'Quantity × price', 'Two decimal places if they can'],
      ['Build a short receipt from three inputs', 'Print naira values clearly'],
      ['Model product, price, qty, total', 'Keep it to one product this week'],
      ['Write a receipt program', 'Print a line like “Rice x 2 = 1600”'],
      'Receipt total equals price times quantity.',
      'Add a second product on paper. You do not have to code it yet.',
      'Inputs used; total is computed.',
    ),
    L(
      ['if / elif / else', 'Indentation', 'and / or'],
      ['Choose a grade band from a score', 'Keep indent even in the else'],
      ['Write the school’s A/B/C/F bands on the board first', 'Show a TabError on purpose'],
      ['Grade a score with if/elif/else', 'Test 49 and 50'],
      '49 and 50 produce different grades if the boundary needs it.',
      'Write the grade bands you coded.',
      'Boundary scores behave as agreed.',
    ),
    L(
      ['for range', 'while', 'A way to stop'],
      ['Print a sequence with for and range', 'Write a while loop that stops'],
      ['Count 1 to 5 two ways', 'Show an infinite loop, then stop it, then add the missing change'],
      ['Print 1 to 10 with for', 'Ask for a password until it matches a secret, with a max of 5 tries if they can'],
      'for loop prints a sequence; while loop ends.',
      'What would happen if you forgot to change the while variable?',
      'Both loops run and finish.',
    ),
    L(
      ['def', 'return versus print', 'A name that is a verb'],
      ['Write a function and call it twice', 'Return a value and use it'],
      ['def celsius_to_f(c): return ...', 'Call it with 0 and 100'],
      ['Write one function used twice', 'Prefer return, print in the caller'],
      'Function is defined once and called more than once.',
      'Write the function name and what it returns.',
      'No copy-paste of the same formula in two places.',
    ),
    L(
      ['A tiny plan', 'Variables, input, if or loop, a function if they can', 'Show it running'],
      ['Build a calculator or a 3-question quiz', 'Test with two different inputs'],
      ['Scope on the board: 40 minutes build, 10 minutes demo', 'Ban new libraries'],
      ['Finish the mini app', 'Demo one run and one edge case'],
      'App runs from a saved file and handles at least two inputs.',
      'Write two test inputs and the output you expect.',
      'Working mini app; pair can run it without the teacher typing.',
    ),
  ],
  [
    L(
      ['list, index', 'append / pop', 'tuple as “do not change”'],
      ['Make a list and print one item by index', 'Add and remove an item'],
      ['Shopping list on the projector', 'Show list[-1] once'],
      ['Build a shopping list program: add, show, remove', 'Print the list after each change'],
      'List changes on add and remove, and print shows the new list.',
      'When would a tuple be better than a list?',
      'Live add/remove with printed list.',
    ),
    L(
      ['dict key and value', 'lookup', 'a set of unique items'],
      ['Store a name → phone (or email) map', 'Print one value by key'],
      ['contacts["Ada"] = "0803..."', 'Misspell a key and read KeyError'],
      ['Build a tiny contacts dict', 'Look up one name the teacher gives'],
      'Lookup prints the right number for a known name.',
      'What should the program say if the name is missing? Write one line.',
      'Dictionary lookup works for a key they stored.',
    ),
    L(
      ['[expr for x in list]', 'a filter in the comprehension', 'enumerate'],
      ['Rewrite a doubling loop as a list comprehension', 'Print index and item with enumerate'],
      ['Show the long for-loop, then the one-liner', 'Do not force filters on everyone'],
      ['Double a list of numbers with a comprehension', 'enumerate a list of names'],
      'Comprehension produces the doubled list.',
      'Write the for-loop version of your comprehension.',
      'Comprehension runs; result is a list.',
    ),
    L(
      ['with open', 'read lines', 'write / append'],
      ['Write a line to a text file', 'Read the file back and print it'],
      ['Create notes.txt in the class folder', 'Show that the file remains after Python closes'],
      ['Append a journal line with today’s date or name', 'Read and print the file'],
      'A real file on disk contains their line.',
      'What is the difference between write and append?',
      'File exists and content matches what they printed.',
    ),
    L(
      ['ValueError', 'try / except', 'Ask again or a clear message'],
      ['Catch a bad int(input()) without crashing', 'Print a useful message'],
      ['Type “ten” into int(input()) and catch it', 'Keep the happy path outside except'],
      ['Wrap their numeric input in try/except', 'Prove it by typing a letter'],
      'Letters at the prompt do not crash the program.',
      'Write the error name you caught.',
      'Safe input demonstrated with invalid text.',
    ),
    L(
      ['Lists or dict plus a file', 'Validate input', 'A save that survives closing Python'],
      ['Save and reload a small set of records', 'Refuse empty names'],
      ['Inventory or contacts, their choice, one file', 'Milestone: save, close, open, data still there'],
      ['Build the file-backed tool', 'Show reload after a restart of the editor'],
      'Data round-trips through a file.',
      'Write the file name and the fields you store.',
      'Reload works; invalid empty input is rejected or asked again.',
    ),
    L(
      ['import math / random', 'a file of their own functions', 'import as'],
      ['Import a built-in module and use one function', 'Import a function from their own .py file'],
      ['random.randint in a dice demo', 'helpers.py next to main.py'],
      ['Use random or math in a tiny program', 'Put one function in a second file and import it'],
      'Second file imports without error.',
      'List the files in your project folder.',
      'Built-in import and a local import both run.',
    ),
    L(
      ['class', '__init__', 'self'],
      ['Define a simple class and make one object', 'Print an attribute'],
      ['class Student: with name and class_level', 'Make two students'],
      ['Create a class with two attributes', 'Make two objects and print them'],
      'Two objects, different data, same class.',
      'What does self mean, in your own words?',
      'Objects print distinct attributes.',
    ),
    L(
      ['a method', 'a child class', 'override if they get that far'],
      ['Add a method that uses self', 'Make one subclass with a different method or extra attribute'],
      ['Vehicle.start(), Car honks', 'Keep inheritance optional if time is short — method is required'],
      ['Add a method to their class', 'If time: a subclass'],
      'Calling the method on an object prints or returns something that uses the object’s data.',
      'Write the method name and what it does.',
      'Working method on an instance.',
    ),
    L(
      ['A small object design', 'One extra skill from the term (file or list)', 'A demo'],
      ['Finish a small OOP program', 'Demo creating objects and calling a method'],
      ['Bank account or school register as examples, not mandatory themes', 'Rubric: class, object, method, runs'],
      ['Finish the term project', 'Demo one object and one method'],
      'Class, at least one object, one method, runs from a file.',
      'Draw the class as a box with attributes and methods.',
      'Rubric met in a live run.',
    ),
  ],
  [
    L(
      ['Editor, save, run', 'print', 'A first file name'],
      ['Run a Python file', 'Print a greeting'],
      ['Same hello path as Term 1 for learners who start now', 'Save as hello.py'],
      ['Print two lines', 'Save and run'],
      'File runs with no traceback.',
      'What folder is your file in?',
      'hello.py runs.',
    ),
    L(
      ['Variables', 'Types', 'Print labels'],
      ['Store and print a number and a piece of text', 'Use names that read like English'],
      ['age = 13; subject = "ICT"', 'Show type() once'],
      ['Three variables, three labelled prints'],
      'Output comes from variables.',
      'Circle the type of each variable in your book.',
      'Variables used correctly.',
    ),
    L(
      ['A small repair', 'Output that a stranger can read', 'Ask for help with the error text'],
      ['Fix two broken programs', 'Print a labelled result'],
      ['Worksheet of two bugs', 'They must read the traceback out loud'],
      ['Repair both programs in pairs'],
      'Both run.',
      'Copy one traceback line you used.',
      'Repairs done in class.',
    ),
    L(
      ['Arithmetic', 'A total', 'An average'],
      ['Add and divide in code', 'Print a total and an average'],
      ['Three scores on the board'],
      ['Compute total and average'],
      'Average is computed.',
      'Predict 9 / 2 in Python.',
      'Correct results printed.',
    ),
    L(
      ['input', 'int conversion', 'A sentence back to the user'],
      ['Ask for a name and a number', 'Use both in a print'],
      ['Live demo, then they write their own question'],
      ['Interactive script with one int conversion'],
      'Program uses typed input.',
      'What if the number is a word?',
      'Interactive run succeeds with a number.',
    ),
    L(
      ['A small calculation with input', 'Clear print', 'One formula'],
      ['Take two numbers and print a result', 'Label the result'],
      ['Area of a rectangle or a two-item bill'],
      ['Build the calculator'],
      'Result matches the inputs.',
      'Write the formula you coded.',
      'Inputs and formula agree.',
    ),
    L(
      ['if', 'else', 'A boundary'],
      ['Choose between two messages with if/else', 'Test both sides'],
      ['Pass mark 50'],
      ['Pass/fail from a typed score', 'Test 49 and 50'],
      'Both sides work.',
      'Write your condition in English.',
      'Boundary tested.',
    ),
    L(
      ['for', 'range', 'A finished loop'],
      ['Print a range with for', 'Loop finishes by itself'],
      ['for i in range(1, 6)'],
      ['Print 1 to 10'],
      'Ten lines, then the prompt comes back.',
      'How would while do the same job?',
      'Loop completes.',
    ),
    L(
      ['def', 'call', 'No copy-paste of the same code'],
      ['Write a function and call it', 'Pass one argument'],
      ['def greet(name):'],
      ['Function plus two calls'],
      'One definition, two calls.',
      'Name your function.',
      'Function used twice.',
    ),
    L(
      ['A short Nigerian scene in code', 'Input or a loop', 'A title'],
      ['Tell a tiny story or quiz in Python', 'Run it for the class'],
      ['Market list, football scores, or a bus fare — their choice', 'Keep it under 40 lines'],
      ['Finish and present My Nigerian Tech Story'],
      'Program runs and the pair can say what a user types and what they see.',
      'Write the title and the user steps.',
      'Presented running program.',
    ),
  ],
];
