import type { SpineCourseMeta, SpineLessonSpec } from '@/lib/curriculum/school-spine-week';

const L = (
  subtopics: string[],
  objectives: string[],
  teacher: string[],
  students: string[],
  classwork: string,
  homework: string,
  check: string,
): SpineLessonSpec => ({
  subtopics,
  objectives,
  teacher,
  students,
  classwork: { title: 'In class', instructions: classwork },
  assignment: { title: 'Before next class', instructions: homework },
  check: { title: 'Look for', how: check },
  resources: ['Scratch 3 (scratch.mit.edu or offline editor)', 'Headphones if the lab is noisy'],
  tips: ['Let pairs share a mouse', 'Ask “what happens if we click this block?” before telling them'],
});

export const SCRATCH_COURSE_META: SpineCourseMeta = {
  title: 'Creative Coding with Scratch',
  overview:
    'Learners build animations, stories and games with Scratch blocks. Each week they make something that runs, then name the idea behind it — sequence, loop, condition, variable — so the next week can use it.',
  outcomes: [
    'Open Scratch, add a sprite and a backdrop, and save a project.',
    'Make a sprite move, change costume and play a sound using events.',
    'Use loops, conditions and variables to finish a small game.',
    'Explain a project in plain words: what the player does and how the blocks make it happen.',
  ],
  materials: ['Computers or tablets with Scratch 3', 'Projector', 'Exercise book for sketches'],
  tools: ['Scratch 3'],
  assessmentStrategy:
    'Weekly working project on screen, a short practical at mid-term, and a finished story or game at the end of term.',
};

export const SCRATCH_LESSONS: SpineLessonSpec[][] = [
  [
    L(
      ['Stage, sprite and blocks palette', 'Starting a project from the cat sprite', 'Saving with the learner’s name'],
      ['Name the stage, a sprite and the scripts area', 'Start a new Scratch project and save it'],
      ['Open Scratch on the projector and point to stage, sprite and blocks', 'Create a class folder name pattern: firstname-scratch-w1'],
      ['Open Scratch and click the cat', 'Save the empty project with their name'],
      'Each pair saves a new project and shows the teacher the file name on screen.',
      'Draw the Scratch window in your book and label stage, sprite and blocks.',
      'Every pair has a saved project the teacher can open next week.',
    ),
    L(
      ['x and y on the stage', 'go to x y / change x by', 'The grid behind the stage'],
      ['Move a sprite to a named place on the stage', 'Say whether a sprite is left, right, up or down of centre'],
      ['Show the mouse x/y readout and move the cat to (0,0), then to a corner', 'Give three target points for learners to hit'],
      ['Use go to x y to park the sprite on three given points', 'Write the x and y of those points in their book'],
      'Park the cat on the three points the teacher lists on the board.',
      'Write two new points you would use to hide a sprite off the stage.',
      'Sprite lands on the asked coordinates without dragging it by hand.',
    ),
    L(
      ['Motion blocks recap', 'A short practical, not a paper test', 'What a finished week-1 and week-2 project looks like'],
      ['Show a sprite that moves to a place when the green flag is clicked', 'Fix a project that will not start'],
      ['Give a 15-minute practical: flag click → sprite goes to a point and says “ready”', 'Sit with pairs whose project does not start'],
      ['Build or repair the practical project', 'Show the teacher the green-flag start'],
      'Green flag makes the sprite move and speak. No extra help after the first try.',
      'Write three reasons a Scratch project might not start.',
      'Working green-flag start and a sprite that actually moves.',
    ),
    L(
      ['Costumes versus backdrops', 'next costume', 'Choosing a backdrop that matches the story'],
      ['Switch a sprite costume on a click or a wait', 'Change the backdrop once in a short scene'],
      ['Show one sprite with two costumes and switch them on a beat', 'Ask learners to pick a backdrop that is not the default'],
      ['Give their sprite at least two costumes', 'Add a backdrop and switch costume twice'],
      'A 6-second scene: backdrop, two costumes, sprite stands still then changes look.',
      'Find one more costume at home or in the library and name when you would use it.',
      'Two costumes and one non-default backdrop in the saved project.',
    ),
    L(
      ['start sound / play sound until done', 'Volume and wait', 'Matching sound to an action'],
      ['Play a sound when the sprite is clicked', 'Wait so sound and movement do not pile up'],
      ['Contrast start sound with play until done on the projector', 'Set a rule: one sound per action this week'],
      ['Add a click sound to their sprite', 'Make the sprite wait until the sound finishes before moving'],
      'Click the sprite: sound plays, then it moves. Not the other way round.',
      'List two sounds that would fit a school story and two that would not.',
      'Sound and movement happen in a clear order.',
    ),
    L(
      ['when green flag clicked', 'when this sprite clicked', 'broadcast / when I receive'],
      ['Start one script from the green flag and another from a click', 'Use one broadcast so a second sprite reacts'],
      ['Build a two-sprite hello: flag starts sprite A, A broadcasts, B answers', 'Name the message out loud before learners copy it'],
      ['Add a second sprite that only moves after it receives a message', 'Keep message names short: hello, next, done'],
      'Two sprites: the second does not move until the first broadcasts.',
      'Write the broadcast name you used and what the second sprite does.',
      'Second sprite stays still until the message arrives.',
    ),
    L(
      ['repeat / forever', 'wait inside a loop', 'A walking or bouncing animation'],
      ['Use a loop so a costume change repeats', 'Stop a forever loop by thinking about when the scene should end'],
      ['Show next costume inside repeat 10 with wait 0.2', 'Warn that forever never ends unless they stop the project'],
      ['Animate a sprite walking or bouncing with a loop', 'Save a version before they try forever'],
      'A looped animation that you can watch for three seconds without clicking again.',
      'In your book: repeat vs forever in one sentence each.',
      'Visible looped animation, not a single costume change.',
    ),
    L(
      ['say / think / wait', 'A beginning, middle and end', 'Click to go to the next line'],
      ['Tell a three-beat story with say blocks and waits', 'Let the player click to continue at least once'],
      ['Model a 4-line story on the projector', 'Ask for a Nigerian setting: market, pitch, classroom, bus'],
      ['Build a three-scene story with one click to continue', 'Use one backdrop change between scenes'],
      'A story that starts on green flag and has a beginning, middle and end.',
      'Write the three sentences your sprite will say next week if you add a fourth scene.',
      'Story runs without the teacher dragging sprites.',
    ),
    L(
      ['A player action (click or key)', 'A goal (touch a sprite or reach a point)', 'A simple win message'],
      ['Make a tiny game with one player action and one goal', 'Show a win message when the goal is met'],
      ['Demo a “catch the star” in two minutes', 'Keep scope tiny: one player sprite, one target'],
      ['Build catch-the-star or a click-the-ball game', 'Add a “You did it” say block'],
      'Player can win the mini-game without restarting Scratch.',
      'Name one rule you would add next (timer, score, or a second target).',
      'A reachable goal and a win message.',
    ),
    L(
      ['Plan on paper first', 'Reuse motion, looks, sound and events', 'Show the class the story'],
      ['Finish an animated story that uses at least four skills from the term', 'Present the story in under one minute'],
      ['Put a four-tick checklist on the board: move, costume, sound, event', 'Time presentations so every pair shows once'],
      ['Finish and save the term story', 'Present: what the player sees, which blocks did the work'],
      'Story uses move, costume or look, sound, and an event. Pair can name those four.',
      'Write two things you would change if you had one more week.',
      'Checklist complete and the project opens from the saved file.',
    ),
  ],
  [
    L(
      ['Make a variable', 'change variable by / set variable to', 'Show the variable on the stage'],
      ['Create a score variable and change it when something happens', 'Show the score on the stage'],
      ['Make Score in front of the class and change it on a click', 'Hide then show the variable so they see the tick box'],
      ['Add Score to their game', 'Increase Score when the player hits the target'],
      'Score starts at 0 and goes up when the player succeeds.',
      'What should happen to Score when the player misses? Write one idea.',
      'Variable visible and changing for a real game event.',
    ),
    L(
      ['if then', 'touching colour or sprite', 'else as a second path'],
      ['Use if then so the sprite does one thing when a condition is true', 'Add an else path for the miss or the wall'],
      ['Build if touching star then score else say try again', 'Read the condition out loud as a sentence'],
      ['Put an if around their win rule', 'Add an else that is not empty'],
      'Two different outcomes: success path and miss path.',
      'Write the if-sentence for your game in English, then in blocks.',
      'Both branches can be demonstrated.',
    ),
    L(
      ['touching sprite / colour', 'key pressed', 'distance or mouse down'],
      ['Detect a collision or a key press with a sensing block', 'Use that sense to change score or scene'],
      ['Show touching colour on a maze wall', 'Let them pick one sense only this week'],
      ['Add one sensing block to the game', 'Prove it by making something happen on touch or key'],
      'A sensing block causes a visible change (bounce, score, or speech).',
      'Name a second sense you did not use and when you would need it.',
      'Sensing is in the script, not only dragging sprites by hand.',
    ),
    L(
      ['pick random', 'arithmetic in a round', 'join for a speech bubble'],
      ['Use pick random for a position or a wait', 'Join text and a variable in a say block'],
      ['Drop a star at pick random x and y', 'Show join Hello and Score'],
      ['Randomise one thing in the game', 'Say a message that includes the score'],
      'Something in the project is different each run because of pick random.',
      'Write the random range you used and why those numbers.',
      'Randomness or join is visible in the running project.',
    ),
    L(
      ['Make a block', 'Define with a name that is a verb', 'Use the block more than once'],
      ['Create one custom block and use it twice', 'Name the block after what it does'],
      ['Make a jump block on the projector and call it twice', 'Reject names like block1'],
      ['Define one custom block', 'Replace two copied scripts with that block'],
      'One named custom block used in two places.',
      'Write the custom block name and the blocks inside it.',
      'Custom block exists and is actually called.',
    ),
    L(
      ['A playable draft, not a new idea', 'Score plus one sense', 'A short playtest with a neighbour'],
      ['Play a neighbour’s game and give one useful comment', 'Fix one bug found in playtest'],
      ['Ten-minute build, five-minute swap, five-minute fix', 'Ban starting a brand new game from zero'],
      ['Improve the current game with score and sensing', 'Swap seats and play a neighbour’s game once'],
      'Neighbour can play the game without a spoken tutorial.',
      'Note one bug you found in a neighbour’s game and how they could fix it.',
      'Playable game with score; one playtest comment written.',
    ),
    L(
      ['create clone of myself', 'when I start as a clone', 'delete this clone'],
      ['Spawn clones as obstacles or coins', 'Delete a clone when it is hit or leaves the stage'],
      ['Demo falling clones that delete at y = -170', 'Warn that forever + clone without delete will freeze the machine'],
      ['Add clones that appear over time', 'Delete clones that are touched or that leave the stage'],
      'Clones appear and disappear. The project still runs after 20 seconds.',
      'What happens if you never delete a clone? Write one sentence.',
      'Clones spawn and delete; project stays responsive.',
    ),
    L(
      ['A timer variable', 'Counting down each second', 'What happens at zero'],
      ['Show a countdown on the stage', 'End the game or the level when the timer hits zero'],
      ['Timer = 10, wait 1, change by -1, if = 0 then broadcast end', 'Keep the timer visible'],
      ['Add a countdown to their game', 'Show a Time up message at zero'],
      'Timer counts down and the game reacts at zero.',
      'Would your game be better with more time or less? Why?',
      'Visible countdown and a clear end at zero.',
    ),
    L(
      ['More than one backdrop as a level', 'broadcast next level', 'Reset score or timer'],
      ['Build two levels with two backdrops', 'Move to level two when a goal is met'],
      ['Show backdrop 1 / backdrop 2 as Level 1 / Level 2', 'Reset player position on level change'],
      ['Add a second maze or room', 'Broadcast to switch level when the door is reached'],
      'Player can reach a second level without the teacher changing the backdrop.',
      'Sketch level 3 on paper even if you do not build it yet.',
      'Two backdrops and a working level change.',
    ),
    L(
      ['A platform or a maze with gravity or walls', 'Score, timer or lives', 'A one-minute demo'],
      ['Finish a platformer or maze that uses clones or a timer', 'Demo the game and name three blocks that matter'],
      ['Rubric on the board: start, play, score or timer, end', 'Keep demos to one minute'],
      ['Finish and save the term game', 'Demo: how to play, how you win, one block you are proud of'],
      'Game starts, can be played, and ends. Pair names three key blocks.',
      'Write a title and two sentences of instructions for a new player.',
      'Rubric met; project opens from the saved file.',
    ),
  ],
  [
    L(
      ['What Scratch is for', 'Green flag and stop', 'A first save'],
      ['Open Scratch and save a named project', 'Run and stop a script with the green flag and stop sign'],
      ['Tour the editor slowly for learners who missed first term', 'Use the same save-name rule as Term 1'],
      ['Open Scratch, click the cat, save', 'Run a say hello script on green flag'],
      'Saved project with a green-flag hello.',
      'Label a sketch of the Scratch window.',
      'Project saved and hello runs from the green flag.',
    ),
    L(
      ['move steps', 'turn', 'when green flag clicked'],
      ['Make a sprite move in a sequence when the flag is clicked', 'Turn the sprite so it faces where it is going'],
      ['Build a square path: move, turn 90, four times', 'Let them try then show the square'],
      ['Move the sprite in at least two directions', 'Use green flag, not only the hat on a click'],
      'Green flag walks the sprite along a path you can see.',
      'How many steps did you use? Why that number?',
      'Sequence of motion blocks runs from the flag.',
    ),
    L(
      ['Can they start a project?', 'Can they move a sprite?', 'Kind feedback, not a rank'],
      ['Start a project from the green flag without help', 'Move a sprite using blocks, not only the mouse'],
      ['Five-minute practical: flag → move → say your name', 'Help only after they have tried once'],
      ['Complete the practical', 'Show the teacher the running script'],
      'Unaided green-flag motion and a say block.',
      'Write one thing that was hard and one thing that worked.',
      'Practical completed on the learner’s own machine or pair machine.',
    ),
    L(
      ['play sound', 'change effect or size', 'A feeling: happy, scared, proud'],
      ['Play a sound that matches a look change', 'Change size or colour for one beat'],
      ['Show looks + sound as a reaction, not decoration', 'Keep it to one effect this week'],
      ['Add a sound and a look change on the same event', 'Save before they stack five effects'],
      'One event triggers both a look and a sound.',
      'Which effect would you remove to make the scene clearer?',
      'Look and sound fire together from one event.',
    ),
    L(
      ['repeat', 'wait inside the loop', 'A spinning or blinking sprite'],
      ['Repeat an action a chosen number of times', 'Put a wait in the loop so the eye can see each turn'],
      ['repeat 8, turn 45, wait 0.2 as a spinner', 'Count the repeats with the class'],
      ['Build a repeating animation', 'Change the repeat number and watch the difference'],
      'Animation clearly repeats; changing the number changes the result.',
      'What would forever do to this spinner? Write one sentence.',
      'Loop is visible and the repeat count was chosen on purpose.',
    ),
    L(
      ['Show a looped animation', 'Name the loop block they used', 'Fix one freeze or one too-fast loop'],
      ['Show a loop that the teacher can see', 'Change wait or repeat to improve it'],
      ['Practical: 30-second looped animation, then one improvement', 'Watch for forever with no wait'],
      ['Present the loop', 'Add or change a wait so it is not a blur'],
      'Looped animation with a wait; learner can point at the loop block.',
      'Draw the loop as a circle in your book and write what sits inside it.',
      'Loop block present and the motion is watchable.',
    ),
    L(
      ['if then', 'A yes/no question the computer can test', 'Touching or key as the test'],
      ['Make the sprite do something only if a condition is true', 'Say the condition as a full sentence'],
      ['If touching the edge then bounce, said in English first', 'One condition only'],
      ['Add if then to their project', 'Read the if out loud to their pair'],
      'Something happens only when the condition is true.',
      'Write your if-sentence in English.',
      'Condition can be shown true and false.',
    ),
    L(
      ['Make a variable', 'set / change', 'Show it on the stage'],
      ['Store a number in a variable', 'Change it when the player does something'],
      ['Lives or clicks as a starter variable', 'Show it on stage from the first minute'],
      ['Create a variable and change it on an event', 'Keep it visible'],
      'Variable appears on stage and the number changes.',
      'Would you use this variable for score, lives, or time? Why?',
      'Visible variable tied to a player action.',
    ),
    L(
      ['Three scenes', 'say and wait', 'One event to start'],
      ['Build a short story that uses sequence and at least one extra skill', 'Tell the class what happens in each scene'],
      ['Cap at three scenes so they finish', 'Checklist: start, two sprites or one costume change, an ending'],
      ['Finish a simple story project', 'Practise a 30-second show-and-tell'],
      'Story runs from green flag to an ending without extra clicks from the teacher.',
      'Write a title for your story.',
      'Complete beginning–middle–end story saved.',
    ),
    L(
      ['What to show', 'What to say', 'What you would do next term'],
      ['Present a finished project', 'Name two blocks you used and why'],
      ['One-minute presentations, kind questions only', 'Mark against: runs, can explain, saved'],
      ['Present the term project', 'Answer: what should the viewer look for?'],
      'Project runs and the pair can name two blocks.',
      'Write one skill you want in the next term.',
      'Presentation done; file saved and openable.',
    ),
  ],
];
