'use client';
import { useCallback, useEffect, useState } from 'react';
import { Loader2, RefreshCw } from 'lucide-react';

type RequestRow = { id: string; email: string; full_name: string | null; account_role: string | null; reason: string | null; status: string; requested_at: string; retention_note: string | null };
export default function AccountDeletionRequestsPage() {
  const [rows, setRows] = useState<RequestRow[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); const r = await fetch('/api/account-deletion?admin=1'); const j = await r.json(); if (!r.ok) setError(j.error || 'Unable to load requests'); else setRows(j.requests || []); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  async function update(id: string, status: string) { setSaving(id); setError(''); const r = await fetch('/api/account-deletion', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); if (!r.ok) setError('Unable to update request'); await load(); setSaving(''); }
  return <div className="space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black">Account deletion requests</h1><p className="mt-1 text-sm text-muted-foreground">Verify ownership, handle required retention, then complete the associated data deletion.</p></div><button onClick={() => void load()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border px-4 font-bold"><RefreshCw className="h-4 w-4" /> Refresh</button></header>{error && <p role="alert" className="rounded-xl bg-rose-500/10 p-4 text-rose-600 dark:text-rose-400">{error}</p>}{loading ? <div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin" /></div> : <div className="grid gap-4">{rows.length === 0 && <div className="rounded-xl border border-border bg-card p-8 text-center text-muted-foreground">No deletion requests.</div>}{rows.map(row => <article key={row.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><h2 className="font-black">{row.full_name || row.email}</h2><p className="text-sm text-muted-foreground">{row.email} · {row.account_role || 'Unknown role'}</p><p className="mt-1 text-xs text-muted-foreground">Requested {new Date(row.requested_at).toLocaleString()}</p></div><span className="h-fit rounded-full bg-muted px-3 py-1 text-xs font-black uppercase">{row.status.replace('_', ' ')}</span></div>{row.reason && <p className="mt-4 rounded-xl bg-muted/40 p-3 text-sm">{row.reason}</p>}<div className="mt-4 flex flex-wrap gap-2">{['in_progress','completed','rejected'].map(status => <button key={status} disabled={saving === row.id || row.status === status} onClick={() => void update(row.id, status)} className="min-h-11 rounded-xl border border-border px-4 text-xs font-black uppercase disabled:opacity-40">{status.replace('_', ' ')}</button>)}</div></article>)}</div>}</div>;
}