/**
 * What goes on a working page.
 *
 * Every session page has the same four parts, and the sameness is the point: a
 * six-year-old who has to relearn the shape of the page each week is spending
 * their attention on the book instead of on the work.
 *
 *   Today — one sentence, what we are doing.
 *   Try it — the thing they do at the machine.
 *   Write it down — the part that ends up on paper, so there is evidence.
 *   Tick — done, and a box a parent can see.
 *
 * Nothing here is generated by a model. The curriculum row supplies the theme,
 * the three termly focuses, the capstone and the portfolio target, and the
 * scaffolds below turn those into pages. A model writing thirty-six activities
 * per year group across twelve year groups would produce four hundred and
 * thirty-two activities nobody has read, printed two hundred times each.
 *
 * The AI engine may eventually draft *variants* of these for a teacher to
 * approve, which is the same shape as `proposal-narrative`: opt-in, validated,
 * and falling back to the authored version. Printing is the wrong place to
 * start that, because paper cannot be corrected after it ships.
 */
import type { ProgressionLevel, ProgressionTerm } from '@/lib/partnerships/curriculum';

export type SessionContent = {
  term: number;
  session: number;
  /** One sentence naming what this session is about. */
  today: string;
  /** What they do at the machine or with the hardware. */
  tryIt: string;
  /** The prompt for the part that ends up written or drawn on the page. */
  writeIt: string;
  /** Ruled lines, a drawing box, or a grid to fill in. */
  workspace: 'lines' | 'box' | 'grid';
};

/**
 * The rhythm of a term, as a repeating four-week cycle.
 *
 * Weeks are not interchangeable. A term that is twelve unrelated activities
 * teaches twelve unrelated things; a term that repeats meet / build / break /
 * show teaches one thing four times, which is how a skill actually forms. The
 * cycle also means a child who misses a week is not lost — next week is a shape
 * they recognise.
 */
const CYCLE = [
  {
    beat: 'meet',
    // Four words at most, and words a six-year-old already owns. The curriculum
    // focus — "Computer hardware basics, Scratch 3.0 UI & smart concepts" — is
    // written for a teacher; setting it as the headline of a Basic 1 page gives
    // a child two lines of vocabulary before they reach anything they can do.
    // It belongs on the term opener, once, where the teacher reads it.
    today: 'Watch and copy',
    tryIt: 'Follow your teacher step by step. Copy exactly what you see on the screen.',
    writeIt: 'Draw what you saw on the screen. Label two things you can name.',
    workspace: 'box' as const,
  },
  {
    beat: 'build',
    today: 'Make it yourself',
    tryIt: 'Make it on your own this time. Your teacher will help only if you ask.',
    writeIt: 'Write the steps you took, in order. Number them 1, 2, 3.',
    workspace: 'lines' as const,
  },
  {
    beat: 'break',
    today: 'Break it, then fix it',
    tryIt: 'Change one thing so it stops working. Then find the change and undo it.',
    writeIt: 'What did you change? What went wrong? How did you fix it?',
    workspace: 'lines' as const,
  },
  {
    beat: 'show',
    today: 'Show someone',
    tryIt: 'Show your work to a partner. Watch them try it without your help.',
    writeIt: 'What did your partner find hard? What will you change next time?',
    workspace: 'grid' as const,
  },
] as const;

/** Every session page for one term, in teaching order. */
export function sessionsForTerm(
  term: ProgressionTerm,
  sessionCount: number,
): SessionContent[] {
  return Array.from({ length: sessionCount }, (_, i) => {
    const beat = CYCLE[i % CYCLE.length];
    return {
      term: term.term,
      session: i + 1,
      today: beat.today,
      tryIt: beat.tryIt,
      writeIt: beat.writeIt,
      workspace: beat.workspace,
    };
  });
}

/** The words a child should be able to use by the end of the year. */
export function glossaryFor(level: ProgressionLevel): string[] {
  // Drawn from the year's own focuses rather than a fixed list, so a glossary
  // never contains a word the book did not teach.
  const words = new Set<string>();
  for (const term of level.terms) {
    for (const raw of term.focus.split(/[,&;]| and /)) {
      const word = raw.trim().replace(/\.$/, '');
      if (word.length >= 3 && word.length <= 34) words.add(word);
    }
  }
  return [...words].slice(0, 12);
}

/**
 * How the book explains itself, on the inside front cover.
 *
 * Addressed to the child, because they are the one holding it. The parent-facing
 * explanation is on the inside back cover, beside the portfolio log, which is
 * the page a parent actually turns to.
 */
export const HOW_THIS_BOOK_WORKS = [
  'Every week has one page. Find the week your teacher says, and work on that page.',
  'The colour pages in the middle are yours to look at. You do not write on those.',
  'On every other page there is a space for you. Write in it, draw in it, cross things out in it. This book is meant to look used.',
  'When you finish a page, tick the box at the bottom. At the end of term you will be able to see everything you made.',
] as const;

export const FOR_THE_PARENT = [
  'This book is your child’s record of what they built this year — not a textbook to be kept clean.',
  'Each page is one taught session. If a page is blank, that session has not happened yet.',
  'The portfolio log opposite is the short version: what they made, and when. It is the page to ask them about.',
] as const;
