/**
 * A one-colour page must be *designed* in one colour.
 *
 * The temptation with a two-ink book is to design every page in colour and let
 * the printer flatten the cheap ones to grey. It looks fine on a screen and
 * arrives as a page where the red "danger" box and the green "correct" box are
 * the same mid-grey, and a six-year-old cannot tell which is which.
 *
 * So mono pages are held to a rule a machine can check: nothing but black,
 * white and greys, and no meaning carried by hue anywhere. Colour pages are
 * exempt — they are printed in colour, at twice the price, precisely so they
 * can use it.
 *
 * This is the same species of guard as `check-page-fit`: the failure is silent
 * and expensive, it is invisible in a browser, and nobody discovers it until a
 * box of two hundred books arrives.
 */

/** Colours that survive a one-ink press: pure greys, black, white, transparent. */
const ALLOWED_KEYWORDS = new Set(['transparent', 'currentcolor', 'inherit', 'none', 'white', 'black']);

export type GreyscaleViolation = {
  /** Which page the offending declaration was found on. */
  page: number;
  /** The colour that will not survive printing in one ink. */
  value: string;
  /** The surrounding declaration, so it can be found and fixed. */
  context: string;
};

/** Is this hex a pure grey — equal red, green and blue channels? */
export function isGreyHex(hex: string): boolean {
  const raw = hex.replace('#', '').trim();
  const full =
    raw.length === 3
      ? raw
          .split('')
          .map((c) => c + c)
          .join('')
      : raw;
  if (full.length !== 6) return false;
  const r = full.slice(0, 2).toLowerCase();
  const g = full.slice(2, 4).toLowerCase();
  const b = full.slice(4, 6).toLowerCase();
  return r === g && g === b;
}

/** Is this rgb()/rgba() a pure grey? */
export function isGreyRgb(value: string): boolean {
  const nums = value.match(/-?\d*\.?\d+/g);
  if (!nums || nums.length < 3) return false;
  const [r, g, b] = nums.slice(0, 3).map(Number);
  return r === g && g === b;
}

/**
 * Every colour in this CSS or markup that a one-ink press cannot reproduce.
 *
 * Deliberately a string scan rather than a parse. The input is generated by our
 * own template, so the shapes are known; a parser would be more correct and
 * would also be a dependency, a build step and a thing to keep in sync with the
 * template. When this stops catching what it should, that is the moment to
 * reach for a real parser.
 */
export function findNonGreyColours(source: string): string[] {
  const found: string[] = [];

  for (const match of source.matchAll(/#[0-9a-fA-F]{3,8}\b/g)) {
    if (!isGreyHex(match[0].slice(0, 7))) found.push(match[0]);
  }
  for (const match of source.matchAll(/rgba?\([^)]*\)/g)) {
    if (!isGreyRgb(match[0])) found.push(match[0]);
  }
  // oklch and hsl carry a hue channel by construction, so any use of them on a
  // mono page is a colour decision whether or not it renders grey today.
  for (const match of source.matchAll(/(?:oklch|hsla?|lab|lch|color-mix)\([^)]*\)/g)) {
    found.push(match[0]);
  }
  for (const match of source.matchAll(/\b(?:color|background|background-color|border-color|fill|stroke)\s*:\s*([a-z]+)\s*[;}"]/gi)) {
    const keyword = match[1].toLowerCase();
    if (!ALLOWED_KEYWORDS.has(keyword)) found.push(keyword);
  }

  return [...new Set(found)];
}

/**
 * Check every page marked mono in a rendered workbook.
 *
 * Pages are found by the class the template stamps on them, so a page that
 * forgets to declare its ink is not silently exempt — it simply is not a mono
 * page, and the costing will disagree with the plan, which the plan test
 * catches instead.
 */
export function findGreyscaleViolations(html: string): GreyscaleViolation[] {
  const violations: GreyscaleViolation[] = [];

  const record = (page: number, source: string) => {
    for (const value of findNonGreyColours(source)) {
      const at = source.indexOf(value);
      violations.push({
        page,
        value,
        context: source.slice(Math.max(0, at - 60), at + value.length + 20).replace(/\s+/g, ' ').trim(),
      });
    }
  };

  /*
    The stylesheet, not just the markup.

    Checking only the page bodies would catch a colour typed into a style
    attribute and miss every colour in the rules that actually paint those
    pages — which is where a real mistake would live, since the template puts
    almost nothing inline. The mono half of the stylesheet is delimited by
    markers so this can read exactly that region: a comment saying "no hues
    below this line" is a promise, and a marker a test reads is a guarantee.
  */
  /*
    Found by index, not by regex, and the difference is not stylistic.

    The markers are CSS comments — `/* mono-ink:start *​/` — and both `/` and `*`
    are regex metacharacters. Interpolated into a pattern they stopped matching
    anything, so the region checked was the empty string and this whole check
    passed while reading nothing at all. The test that asserts the region is
    non-empty is what found it.
  */
  const from = html.indexOf(MONO_INK_START);
  const to = html.indexOf(MONO_INK_END);
  if (from >= 0 && to > from) {
    record(0, html.slice(from + MONO_INK_START.length, to));
  }

  const pages = [...html.matchAll(/<section class="page page-mono"[^>]*>([\s\S]*?)<\/section>/g)];
  pages.forEach((page, index) => record(index + 1, page[1]));

  return violations;
}

/**
 * Markers around the one-ink half of the stylesheet.
 *
 * Page 0 in a violation means the stylesheet rather than a page body.
 */
export const MONO_INK_START = '/* mono-ink:start */';
export const MONO_INK_END = '/* mono-ink:end */';
